### ISSUE TITLE
Redo Templates + Guide

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-templates#2]
@radu-themeisle so this was the issue I was talking about in Slack. We should redo all the blocks using `max-width` - a few things:

1. We should document this process so we can follow the same guidelines for all future templates.

2. We should follow the same nested-structure of the current blocks.

3. Use the same width for all the sections, and don't use columns for empty spaces like in Hestia and Neve.

4. You can make a readme.md with some guidelines that you think are required for the future uses.

You can start doing with one or two for testing and once we're satisfied with them you can do all of them.

If you got any questions, hit them at me (not on my face).

**Comment by radu-themeisle** [comment]
@HardeepAsrani maybe this should be handled by @rodica-andronache's team as it's related to Themes and import/starter content?
What do you think @rodica-andronache? My idea is that you've already started putting in place a process related to starter content so we should keep all things related in the same boat.

**Comment by rodica-andronache** [comment]
@radu-themeisle if you or anyone else have time for this, please go for it, I'm sure you'll do a great job 👍 I  don't feel we have enough time for this at this moment, so if you could help that would be great

**Comment by radu-themeisle** [comment]
Ok, maybe towards the end of next week I'll free up a bit so I can tackle this. Thank you for your input @rodica-andronache 😎
